export default interface ICharacter {
    id: number,
    //userId: number,
    campaignId: number,
    name: string,
    surname: string,
    raceId: number,
    classId: number,
    strength: number,
    dexterity: number,
    condition: number,
    wisdom: number,
    inteligence: number,
    charisma: number,
    level: number,
    HP: number
    // character: number,
    // AC: number,
    // initiative: number,
    // speed: number,
    // maxHP: number,
    // currentHP: number,
    // temporaryHP: number,
    // skills: string[],
    // atuts: string[],
    // items: number[],
    // age: number,
    // skin: string,
    // hair: string,
    // weight: number,
    // height: number,
    // eyeColour: string,
    // allies: string[],
    // money: number[],
    // XP: number
}